cabal-version:      3.0
name:               asic-llm-clash
version:            0.1.0.0
build-type:         Simple

library
  exposed-modules:    FixedLLM
  hs-source-dirs:      src
  build-depends:       base >=4.14 && <5,
                       clash-prelude >=1.8 && <1.10
  default-language:    Haskell2010
  ghc-options:         -Wall

test-suite fixed-llm-test
  type:                exitcode-stdio-1.0
  main-is:             Spec.hs
  hs-source-dirs:      test
  build-depends:       base >=4.14 && <5,
                       clash-prelude >=1.8 && <1.10,
                       asic-llm-clash
  default-language:    Haskell2010
  ghc-options:         -Wall

